### ISSUE TITLE
How do I get this project running?

### ISSUE THREAD

**Issue by Systemac** [Sjord/get-rich-slowly#7]
Hello, where is the "requests" py in the installation ?

**Comment by Sjord** [comment]
You can install the [requests](http://docs.python-requests.org/en/master/) module like this:

    pip install requests

It may be useful to do this in a [virtual env](https://docs.python.org/3/library/venv.html).

**Comment by Systemac** [comment]
Thank you very much, sorry I forget the right way, thank you for your work and happy new year to you.

I have one last question, whatever module I'm trying to launch, I always have an error with __main__.config, main is not a package. 
Any idea ???

**Comment by Systemac** [comment]
Thank you very much, sorry I forget the right way, thank you for your work and happy new year to you.

On the other hand, sorry, I have no idea how the script works or what dependencies (php, css etc) it would be possible to have more explanation????

**Comment by Systemac** [comment]
Thank you very much, I am working on the translation of the code as I do not use the "NL" thanks again for your work I am starting to understand:)

**Comment by Systemac** [comment]
![sans titre](https://user-images.githubusercontent.com/7353752/50891351-5c231480-13fc-11e9-8177-714446d0e0b9.png)
This error could be due to a no-unicode character in French????

**Comment by Sjord** [comment]
This error is because the data files don't exist yet. Create these two files:

*    data/portfolio_history.json
 *   data/money_history.json

They also should contain valid JSON, so make sure they contain `{}`.

**Comment by Systemac** [comment]
Just for two hugs, well I just finished translating and I have the result in both json, now I'll see how to consult the graph ^^ thank you very much anyway it's very instructive beyond being a great job :)
